# Generated by Django 5.2.4 on 2025-07-15 00:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='email_usuario',
            field=models.EmailField(blank=True, help_text='Email do usuário quando não logado', max_length=254, verbose_name='Email do Usuário'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='nome_usuario',
            field=models.CharField(blank=True, help_text='Nome do usuário quando não logado', max_length=100, verbose_name='Nome do Usuário'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário logado que criou o relatório', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.CreateModel(
            name='ImagemRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Formatos suportados: JPG, PNG, GIF. Tamanho máximo: 5MB', upload_to=core.models.relatorio_imagem_path, verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, help_text='Descrição opcional da imagem', max_length=200, verbose_name='Legenda')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição da imagem no relatório', verbose_name='Ordem')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_relatorio', to='core.relatorio', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Imagem do Relatório',
                'verbose_name_plural': 'Imagens dos Relatórios',
                'ordering': ['ordem', 'data_upload'],
            },
        ),
    ]
