# Generated by Django 5.2.4 on 2025-07-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_relatorio_email_usuario_relatorio_nome_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço da localização do relatório', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude da localização do relatório', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude da localização do relatório', max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
